### PR TITLE
13 fix nav bar and scaling

### LINKED ISSUE #13: Fix nav bar scaling and rename grid
Fix link scaling on different devices. Currently the links are pressing against the nav bar title text. 

Also change grid v2 import

### PR DESCRIPTION
**Pull request by Cesar863**
Fixed nav bar

### CODE REVIEW

File: src/components/Navbar/Navbar.tsx [hunk 1]
```diff
@@ -30,13 +32,13 @@ export const Navbar = () => {
...
 
-  const linkItems = ['Inbox', 'Starred', 'Send email', 'Drafts'];
+  const linkItems = ['About', 'Contact us', 'Services', 'Resources'];
 
   const MobileDrawerList = (
     <List>
       {linkItems.map((text) => (
         <ListItem key={text} disablePadding>
-          <ListItemButton>
+          <ListItemButton sx={{ textAlign: 'right' }}>
```
Comment (noel-pena) [inline src/components/Navbar/Navbar.tsx:42]: We should probably 'left' align this for consistency.

File: src/components/Navbar/Navbar.tsx [hunk 2]
```diff
@@ -119,8 +131,8 @@ export const Navbar = () => {
                   ))}
                 </Stack>
```
Comment (noel-pena) [inline src/components/Navbar/Navbar.tsx]: The middle text  in the app bar currently lays over the items when you minimize to around 700px and although we have not decided on what's going there we should start laying out clickable buttons like so:
```suggestion
  <List sx={{display: 'flex', flexDirection: 'row', justifyContent: 'flex-end', width:'100%', gap: '4px'}}>
    {linkItems.map((text) => (
        <MenuItem sx={{p: 1}} key={text} disableGutters>
          {text}
        </MenuItem>
    ))}
  </List>
```

There's other changes we can make to make the middle text fit which I will leave a comment on.

File: src/components/Navbar/Navbar.tsx [hunk 3]
```diff
@@ -47,38 +49,36 @@ export const Navbar = () => {
...
+                    alt="Logo for Koalaty Speech and Feeding."
+                  />
+                </IconButton>
+              </Grid>
             )}
-            <Grid2
-              size={{ xs: 5, md: 4 }}
+
+            <Grid size={{ xs: 11, md: 4 }} alignContent={'center'}>
+              <Typography
```
Comment (noel-pena) [inline src/components/Navbar/Navbar.tsx:69]: The text is too big for the length of characters. We can default it to `subtitle1`:
```suggestion
  <Typography
      variant='subtitle1'
      textAlign={isMobile ? 'left' : 'center'}
      color={theme.palette.background.default}
      px={2}
  >
```

File: src/components/Navbar/Navbar.tsx [hunk 4]
```diff
@@ -47,38 +49,36 @@ export const Navbar = () => {
...
-                  textAlign="center"
-                  color="white"
-                  px={2}
-                >
-                  Koalaty Speech and Feeding Therapy Services
-                </Typography>
-              </Grid2>
+              <Grid size={{ md: 4 }}>
+                <IconButton size="large" edge="start" color="inherit">
+                  <Image
```
Comment (noel-pena) [inline src/components/Navbar/Navbar.tsx:58]: There is not enough contrast between the logo color and the foreground. If we're keeping a green drawer the logo needs to be darker.

File: src/components/Navbar/Navbar.tsx [hunk 5]
```diff
@@ -30,13 +32,13 @@ export const Navbar = () => {
 
   const isMobile = useMediaQuery(theme.breakpoints.down('md'));
 
-  const linkItems = ['Inbox', 'Starred', 'Send email', 'Drafts'];
+  const linkItems = ['About', 'Contact us', 'Services', 'Resources'];
```
Comment (noel-pena) [inline src/components/Navbar/Navbar.tsx]:
```suggestion
  const linkItems = ['About', 'Contact', 'Services', 'Resources'];
```

File: src/components/Navbar/Navbar.tsx (hunk 1 above)
Comment (Cesar863) [reply src/components/Navbar/Navbar.tsx:42]: If we style the button to look more like a button we can align it right if we need to. I am not sure if this is the final design we have for the Drawer. Need design input from you

File: src/components/Navbar/Navbar.tsx (hunk 4 above)
Comment (Cesar863) [reply src/components/Navbar/Navbar.tsx:58]: This needs technical design and I assume would have to be revised after finishing this story. 

https://github.com/Cesar863/koalaty-speech-and-feeding/issues/19

File: src/components/Navbar/Navbar.tsx (hunk 3 above)
Comment (Cesar863) [reply src/components/Navbar/Navbar.tsx:69]: Can you post a screen shot of this? now it seems to small in desktop mode.

File: src/components/Navbar/Navbar.tsx (hunk 2 above)
Comment (Cesar863) [reply src/components/Navbar/Navbar.tsx]: Good catch made the change

File: src/components/Navbar/Navbar.tsx (hunk 4 above)
Comment (noel-pena) [reply src/components/Navbar/Navbar.tsx:58]: That would be for the page not the drawer. I'll just make an issue for it now.

File: src/components/Navbar/Navbar.tsx (hunk 3 above)
Comment (noel-pena) [reply src/components/Navbar/Navbar.tsx:69]: The purpose is to just make the font smaller since the text is very long. I would say try using a different font size if it's too small then

File: src/components/Navbar/Navbar.tsx (hunk 1 above)
Comment (noel-pena) [reply src/components/Navbar/Navbar.tsx:42]: Might need to see what you mean by that. I'll resolve this for now

File: src/components/Navbar/Navbar.tsx (hunk 4 above)
Comment (Cesar863) [reply src/components/Navbar/Navbar.tsx:58]: I think you should have the say in all final design. I am purposefully not changing colors on ant components until we can go over some color schemes.

File: src/components/Navbar/Navbar.tsx (hunk 3 above)
Comment (noel-pena) [reply src/components/Navbar/Navbar.tsx:69]: We can review this later when we add an actual logo text here.

**Review by noel-pena — APPROVED** [review]
